name: default
root: ~/Developer
startup_window: editor
windows:
  - editor:
      layout: main-horizontal
      panes:
        - nvim
        -
      options:
        main-pane-height: 75
  - git:
      panes:
        - gitui
  - monitoring:
      panes:
        - btop
